default: &default
  adapter: postgresql
  pool: 60
  timeout: 300
  encoding: utf8
  host: localhost
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: camera-store-development

test:
  <<: *default
  database: camera-store-test

production:
  <<: *default
