default: &default
  adapter: postgresql
  pool: 60
  timeout: 300
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: camera-store-development
  user: kptest
  password: myway123

test:
  <<: *default
  database: camera-store-test
  user: kptest
  password: myway123

production:
  <<: *default
